server:
  port: 8001
spring:
  application:
    name: Student-Service
  boot:
    admin:
      client:
        url: http://localhost:9999
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
  datasource:
    password: toor123@
    url: jdbc:mysql://localhost:3306/lpu
    username: root