server:
  port: 8082
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
        
  application:
    name: rabbit-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672  
  jpa:    
    hibernate:      
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/lpu
    username: root
    password: toor123@
    driver-class-name: com.mysql.jdbc.Driver